New functionality, refreshes the ListView to change data in prop onFetch
FaridSafi/react-native-gifted-listview pull request #43
Opened 2016-06-02 05:09 UTC by debian789

Update the view if a parameter is changed in callback in props onFetch

This allows you to create a search engine that implements a ListView

```

constructor (props) {
  super(props)
  this.state = {
    searchText: 'Hi',
    forceUpdate: false
  }
}

_onFetch(textSerch, page = 1, callback, options) {
  client.newPappers( {search: textSearch, page: page}, function (err, data) {
    if (!err) {
       callback(data.results);
    }
  })
 }

 onSearchChange (event) {
   var textSearch = event.nativeEvent.text.toLowerCase()
   this.setState({searchText: textSearch, forceUpdate: true})
 }

render () {
  return (<View>
<SearchBar
          onSearchChange={this.onSearchChange.bind(this)}
          isLoading={this.state.isLoading}
          onFocus={() =>
             this.refs.listview2 && this.refs.listview2.getScrollResponder().scrollTo(0, 0)}
       />
<GiftedListView
    rowView= {this._renderRowView.bind(this)}
    onFetch= {this._onFetch.bind(this, this.props.textSearch)}
    firstLoader={true} // display a loader for the first fetching
    pagination={true} // enable infinite scrolling using touch to load more
    refreshable={true} // enable pull-to-refresh for iOS and touch-to-refresh for Android
    withSections={false} // enable sections
    forceUpdate={this.props.forceUpdate}
    customStyles={{
      paginationView: {
        backgroundColor: 'red',
        marginBottom: 50
     },
    }}
    refreshableTintColor="blue"
    /></View>)
}
```

2016-09-01 01:36 UTC, skyFi commented
+1

2016-09-23 12:15 UTC, nxtpool approved these changes

2016-09-24 12:33 UTC, K0den commented on GiftedListView.js
> +  componentWillReceiveProps() {
Change this to `componentWillReceiveProps(nextProps)`

2016-09-24 12:35 UTC, K0den commented on GiftedListView.js
> +    if (this.props.forceUpdate) {
And the change this to `nextProps.forceUpdate` otherwise you need two cycles before it updates

2016-09-24 12:37 UTC, K0den requested changes
Use nextProps params. Have you tried to run your example? I haven't but you are switching between using this.state and this.props so I don't think it'll work

2016-09-24 14:38 UTC, debian789 commented on GiftedListView.js
> +  componentWillReceiveProps() {
update with nextProps

2016-09-24 14:38 UTC, debian789 commented on GiftedListView.js
> +    if (this.props.forceUpdate) {
change with nextProps

2016-09-24 14:41 UTC, K0den approved these changes

2016-09-24 14:42 UTC, K0den commented
Then we just need @FaridSafi to wake up or give someone else write access :)

2016-10-03 17:53 UTC, sjafri5 reviewed
when I was running this change I was getting a lot of glitchiness ( the load circle would almost come up and then wouldnt) because of the setState call on line 207. This means even when there's a minor state change the load bar will began to pull up. I remove lines 207-209 and that solved the issue. Otherwise works great.

2017-09-28 12:50 UTC, merged